#!/bin/sh

# This file is part of coremux.
#
# coremux is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# coremux is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with coremux.  If not, see <http://www.gnu.org/licenses/>.


export server=$1

ssh -t -t $server\
    docker run --name mosh-proxy \
    --net=host \
    -tid \
    -v /home/core/.ssh:/root/.ssh \
    -e SSH_CONNECTION \
    -e TERM=xterm-256color \
    thearthur/mosh-proxy:4a779544d0a68edba2d4716e6dc48ee8e161af54 sh -lc tmux;
mosh --server='docker exec -ti mosh-proxy sh -c "sleep 1; mosh-server"' $server 
